name: Deploy gh-pages
on:
  push:
    branches:
      - master

jobs:
  run:
    name: Deploy gh-pages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.repository.default_branch }}
          fetch-depth: 0
          token: ${{ secrets.PIPELINE_BOT_PAT }}

      - name: Set Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install npm dependencies
        run: npm ci

      - name: Deploy Pages
        env:
          TOKEN: ${{ secrets.PIPIELINE_BOT_PAT }}
          REPO: ${{ github.repository }}
        run: |
          git remote set-url origin https://git:${TOKEN}@github.com/${REPO}.git
          npm run deploy -- -u "im-pipeline-bot <73202619+im-pipeline-bot@users.noreply.github.com>"
