name: Run tests
on: [push, pull_request]

jobs:
  run:
    name: Node ${{ matrix.node }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [8, 10, 12]

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 3

      - name: Set Node.js version
        uses: actions/setup-node@v1.1.0
        with:
          version: ${{ matrix.node }}

      - run: node --version
      - run: npm --version
      - run: java -version

      - name: Install npm dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Run bundlesize
        run: npm run bundlesize
        if: matrix.node == 10 && github.repository == 'twbs/bootstrap' && github.event_name == 'push'
        env:
          BUNDLESIZE_GITHUB_TOKEN: "${{ secrets.BUNDLESIZE_GITHUB_TOKEN }}"

      - name: Run BrowserStack tests
        run: npm run js-test-cloud
        if: matrix.node == 10 && github.repository == 'twbs/bootstrap' && github.event_name == 'push'
        env:
          BROWSER_STACK_ACCESS_KEY: "${{ secrets.BROWSER_STACK_ACCESS_KEY }}"
          BROWSER_STACK_USERNAME: "${{ secrets.BROWSER_STACK_USERNAME }}"

      - name: Run Coveralls
        run: npm run coveralls
        if: matrix.node == 10 && github.repository == 'twbs/bootstrap' && github.event_name == 'push'
        env:
          COVERALLS_REPO_TOKEN: "${{ secrets.COVERALLS_REPO_TOKEN }}"
